#!/bin/bash

. helpers.sh

packages=(
#- dependencies
  'sed' # stream editor
#-

#- core (essential)
  'base' # system packages
  'linux' # kernel
  'linux-headers' # kernel headers
  'sudo' # superuser do
#-

#- console
  'kitty' # terminal emulator
#-

#- audio
  'pulseaudio' # audio server
  'pavucontrol' # audio ui
#-

#- networking
  'networkmanager' # wifi
  'network-manager-applet' # wifi ui
#-

#- bluetooth
  'bluez' # bluetooth protocol stack
  'blueberry' # bluetooth ui
#-

#- window manager/desktop environment
  'xorg-server' # x server
  'xorg-xinit' # start x
  'i3' # i3 window manager
  'i3blocks' # i3bar blocks
#-

#- text editor
  'vim' # vi improved
#

#- browser
  'firefox'
#
)

[[ $BOOTLOADER == 'grub' ]]&& packages+=('grub' 'os-prober') # bootloader
case $UCODE in
  amd-ucode) packages+=('amd-ucode');; # amd microcode updates
  intel-ucode) packages+=('intel-ucode');; # intel microcode updates
esac

#timedatectl set-ntp true

lsblk -o NAME,FSTYPE,MOUNTPOINTS,SIZE

read -rp 'Enter desired disk block device path e.g. /dev/sda, to auto-partition (consume entire disk); Leave blank to skip/manually partition: '
[[ $REPLY ]]&&{ diskBlockPath="/dev/${REPLY#/dev/}"; . auto-part.sh; }

mountpoint -q /mnt||{ printf 'Root filesystem not mounted on /mnt\n'; exit 1; }

[[ -f /mnt/boot/"$UCODE".img ]]&& rm /mnt/boot/"$UCODE".img
pacstrap -MG /mnt "${packages[@]}"

genfstab -U /mnt >/mnt/etc/fstab

cp {chroot,helpers}.sh /mnt/
cp -r /etc/{pacman.conf,pacman.d} /mnt/etc/
arch-chroot /mnt bash chroot.sh
