#!/bin/bash

#set -eEu

networking=0
locale=0
bootloader=0

networkingOptions=(
  'iwd' # iwctl
  'networkmanager (recommended)' # nmcli/nmtui
  'wpa_supplicant' # systemd-networkd
)

while read -r line; do
  if (( ${i:=0} == 18 )); then
    localeOptions+=("${line#\#}")
  else
    ((i++))
  fi
done </etc/locale.gen
unset i line

selectedLocale= # locales to be generated

installPackages=(
  'base' # system
  'linux' 'linux-firmware' 'linux-headers' # ker
  'kitty' # terminal
  'pulseaudio' # audio
  'bluez' # bluetooth
  'sudo' # superuser
  'vim' # editor
  'hyprland' # compositor/wm
  'hyprpaper' # wallpaper setter
  'waybar' # status bar
)

for _ in src/*; do
  : "${_#src/}"; : "${_%.sh}"
  [[ $_ == 'utils' ]]|| options+=("${_^}")
done

. src/utils.sh

: '/sys/firmware/efi/fw_platform_size'
[[ -f $_ ]]&& read -rn 2 <"$_"
if (( $REPLY == 64 )); then
  _msg 'System booted in UEFI mode; Bootloader set to systemd-boot.'
else
  _msg 'System booted in BIOS or CSM mode; Bootloader set to GRUB.'
  installedPackages+=('grub')
fi

timedatectl set-ntp true
timedatectl status

if [[ -d /mnt/boot ]]; then
  _msg 'Boot partition found!'
else
  _fatal 'No boot partition found!'
fi

if [[ -d /mnt/root ]]; then
  _msg "$(df -t --noheadings /mnt) root partition found!"
else
  _fatal 'No root partition found!'
fi

swapon --show|| _warn 'No swap partition or file found!'

# mirrors

_msg "Installing ${#installedPackages[@]} packages to new root!"
pacstrap -K

init_term
draw_opts options
sbar

cursor="$ROWS"
for((;;)){
  hover_opts

  getin
  basic_keymap||{
    case $IN in
      l|\[C)
        for _ in "${options[@]% *}"; do
          [[ $HOVER == "$_" ]]&& . "src/${HOVER,}.sh"
        done
      ;;
      *) PAUSE=1;;
    esac
  }

  scroll_opts
}
