#!/bin/bash

installPackages=(
  'base' # system
  'linux' 'linux-firmware' 'linux-headers' # kernel
  'kitty' # terminal
  'pulseaudio' # audio
  'bluez' # bluetooth
  'sudo' # superuser
  'vim' # editor
  'hyprland' # compositor/wm
  'hyprpaper' # wallpaper setter
  'waybar' # status bar
)
bootloaderOptions=(
  'grub' # bios & grub
  'syslinux' # bios
  'systemd-boot' # uefi
)
networkingOptions=(
  'networkmanager' # nmcli/nmtui
  'iwd' # iwctl
)
stagedPackages=() # packages staged for install
selectedTimezones=() # timezones to add
selectedLocales=() # locales to be generated

for _ in /usr/share/zoneinfo/*; do
  : "${_##*/}"; timezoneOptions+=("$_")
done

i=0
while read -r line; do
  if (( i == 18 )); then
    localeOptions+=("${line#\#}")
  else
    ((i++))
  fi
done </etc/locale.gen

i=0
for _ in src/*; do
  : "${_#src/}"; : "${_%.sh}"

  [[ $_ == 'utils' ]]||{
    options+=("${_^}") STAGED["$_"]="$i"
    ((i++))
  }
done

. src/utils.sh

init_term
draw_opts options
sbar

cursor="$ROWS"
for((;;)){
  hover_opts

  getin
  basic_keymap||{
    case $IN in
      l|\[C)
        for _ in "${options[@]% *}"; do
          [[ $HOVER == "$_" ]]&& . "src/${HOVER,}.sh"
        done
      ;;
      *) PAUSE=1;;
    esac
  }

  scroll_opts
}
